### ISSUE TITLE
earthquakeソースコードをアップしました

### ISSUE THREAD

**Issue by chiru1221** [umepy/EarthquakeLabwork#2]
特徴量として平均、分散、最頻値、中央値、最大、最小を用いました。
個人的には、歪度、尖度を加えて、ランダムフォレストの重要度が低かった最頻値、中央値を除こうと考えています。

ご意見お願いします。

**Comment by umepy** [comment]
よくできてると思います！
ランダムフォレストであれば、重要度の低い要素の排除は精度の向上にあまり貢献しないので、特徴量をどんどん作成・追加していく方向で色々実験していくといいと思います。
また、自分の評価環境とkaggleの評価環境の乖離が大きいとまずいので、一旦kaggleに提出して、評価値の乖離が起きていないか確かめてみてください。

**Comment by chiru1221** [comment]
ありがとうございます！
kaggleのスコアが1.608、自分の評価が2.154でした
自分の評価が上がると、kaggleのスコアもちゃんと上がることは確認できているので問題はないと思っています。
ランダムフォレストの件、了解しました。特徴量を増やす方向でやってみます
