### ISSUE TITLE
自動車走行距離問題のソースコードをアップしました

### ISSUE THREAD

**Issue by yoshinorihanada** [umepy/EarthquakeLabwork#3]
今回アップしたファイルは2つあります。一つ目は重回帰分析で結果を出しました。さらに重回帰分析で改善する場合どのようにすればいいでしょうか。二つ目のファイル名はcar_rf.ipynbで梅本さんがあげてくれた例を拡張したものです。拡張といっても特徴量の重要性を図にしただけなので今後どのように分析を進めていけばいいかのアドバイスをお願いします。

**Comment by umepy** [comment]
作業お疲れ様です！
アップされたファイルを見ました、データの可視化やモデル作成→予測まで出来ていて良いと思います！

今後の方針ですが、重回帰分析とRandomForestではモデルが違うというだけで、方針はほぼ一緒です。予測精度を向上させるには、基本的には特徴量の作成が必要です。
ただし現状、特徴量を作成して追加してもどれくらい予測できているのか？という尺度を測れていません。実際の分析では、持っているデータをまず6:4や8:2ぐらいに分割し、前者を訓練データ、後者をテストデータとします。
今回までにやってもらったファイルでは全てのデータを訓練データとして、モデルを学習していますが、分割したデータのみでモデルを学習し、テストデータを予測させることでどれ程予測できるのかという点を測ることができます。
